export interface Country {
  label: string;
  code: string;
}

export const countries: Country[] = [
  { label: "Afghanistan", code: "AF" },
  { label: "Ägypten", code: "EG" },
  { label: "Albanien", code: "AL" },
  { label: "Algerien", code: "DZ" },
  { label: "Andorra", code: "AD" },
  { label: "Angola", code: "AO" },
  { label: "Antigua und Barbuda", code: "AG" },
  { label: "Äquatorialguinea", code: "GQ" },
  { label: "Argentinien", code: "AR" },
  { label: "Armenien", code: "AM" },
  { label: "Aserbaidschan", code: "AZ" },
  { label: "Äthiopien", code: "ET" },
  { label: "Australien", code: "AU" },
  { label: "Bahamas", code: "BS" },
  { label: "Bahrain", code: "BH" },
  { label: "Bangladesch", code: "BD" },
  { label: "Barbados", code: "BB" },
  { label: "Belgien", code: "BE" },
  { label: "Belize", code: "BZ" },
  { label: "Benin", code: "BJ" },
  { label: "Bhutan", code: "BT" },
  { label: "Bolivien", code: "BO" },
  { label: "Bosnien und Herzegowina", code: "BA" },
  { label: "Botsuana", code: "BW" },
  { label: "Brasilien", code: "BR" },
  { label: "Brunei Darussalam", code: "BN" },
  { label: "Bulgarien", code: "BG" },
  { label: "Burkina Faso", code: "BF" },
  { label: "Burundi", code: "BI" },
  { label: "Chile", code: "CL" },
  { label: "China", code: "CN" },
  { label: "Costa Rica", code: "CR" },
  { label: "Dänemark", code: "DK" },
  { label: "Deutschland", code: "DE" },
  { label: "Dominica", code: "DM" },
  { label: "Dominikanische Republik", code: "DO" },
  { label: "Ecuador", code: "EC" },
  { label: "El Salvador", code: "SV" },
  { label: "Elfenbeinküste", code: "CI" },
  { label: "Eritrea", code: "ER" },
  { label: "Estland", code: "EE" },
  { label: "Eswatini", code: "SZ" },
  { label: "Fidschi", code: "FJ" },
  { label: "Finnland", code: "FI" },
  { label: "Frankreich", code: "FR" },
  { label: "Französisch-Guayana", code: "GF" },
  { label: "Französisch-Polynesien", code: "PF" },
  { label: "Gabun", code: "GA" },
  { label: "Gambia", code: "GM" },
  { label: "Georgien", code: "GE" },
  { label: "Ghana", code: "GH" },
  { label: "Gibraltar", code: "GI" },
  { label: "Grenada", code: "GD" },
  { label: "Griechenland", code: "GR" },
  { label: "Grönland", code: "GL" },
  { label: "Guadeloupe", code: "GP" },
  { label: "Guam", code: "GU" },
  { label: "Guatemala", code: "GT" },
  { label: "Guernsey", code: "GG" },
  { label: "Guinea", code: "GN" },
  { label: "Guinea-Bissau", code: "GW" },
  { label: "Guyana", code: "GY" },
  { label: "Haiti", code: "HT" },
  { label: "Honduras", code: "HN" },
  { label: "Hongkong", code: "HK" },
  { label: "Indien", code: "IN" },
  { label: "Indonesien", code: "ID" },
  { label: "Irak", code: "IQ" },
  { label: "Iran", code: "IR" },
  { label: "Irland", code: "IE" },
  { label: "Island", code: "IS" },
  { label: "Israel", code: "IL" },
  { label: "Italien", code: "IT" },
  { label: "Jamaika", code: "JM" },
  { label: "Japan", code: "JP" },
  { label: "Jemen", code: "YE" },
  { label: "Jersey", code: "JE" },
  { label: "Jordanien", code: "JO" },
  { label: "Kambodscha", code: "KH" },
  { label: "Kamerun", code: "CM" },
  { label: "Kanada", code: "CA" },
  { label: "Kap Verde", code: "CV" },
  { label: "Kasachstan", code: "KZ" },
  { label: "Katar", code: "QA" },
  { label: "Kenia", code: "KE" },
  { label: "Kirgisistan", code: "KG" },
  { label: "Kiribati", code: "KI" },
  { label: "Kolumbien", code: "CO" },
  { label: "Komoren", code: "KM" },
  { label: "Kongo, Demokratische Republik", code: "CD" },
  { label: "Kongo, Republik", code: "CG" },
  { label: "Korea, Nord", code: "KP" },
  { label: "Korea, Süd", code: "KR" },
  { label: "Kosovo", code: "XK" },
  { label: "Kroatien", code: "HR" },
  { label: "Kuba", code: "CU" },
  { label: "Kuwait", code: "KW" },
  { label: "Laos", code: "LA" },
  { label: "Lesotho", code: "LS" },
  { label: "Lettland", code: "LV" },
  { label: "Libanon", code: "LB" },
  { label: "Liberia", code: "LR" },
  { label: "Libyen", code: "LY" },
  { label: "Liechtenstein", code: "LI" },
  { label: "Litauen", code: "LT" },
  { label: "Luxemburg", code: "LU" },
  { label: "Macau", code: "MO" },
  { label: "Madagaskar", code: "MG" },
  { label: "Malawi", code: "MW" },
  { label: "Malaysia", code: "MY" },
  { label: "Malediven", code: "MV" },
  { label: "Mali", code: "ML" },
  { label: "Malta", code: "MT" },
  { label: "Marokko", code: "MA" },
  { label: "Marshallinseln", code: "MH" },
  { label: "Martinique", code: "MQ" },
  { label: "Mauretanien", code: "MR" },
  { label: "Mauritius", code: "MU" },
  { label: "Mayotte", code: "YT" },
  { label: "Mexiko", code: "MX" },
  { label: "Mikronesien", code: "FM" },
  { label: "Moldau", code: "MD" },
  { label: "Monaco", code: "MC" },
  { label: "Mongolei", code: "MN" },
  { label: "Montenegro", code: "ME" },
  { label: "Montserrat", code: "MS" },
  { label: "Mosambik", code: "MZ" },
  { label: "Myanmar", code: "MM" },
  { label: "Namibia", code: "NA" },
  { label: "Nauru", code: "NR" },
  { label: "Nepal", code: "NP" },
  { label: "Neukaledonien", code: "NC" },
  { label: "Neuseeland", code: "NZ" },
  { label: "Nicaragua", code: "NI" },
  { label: "Niederlande", code: "NL" },
  { label: "Niger", code: "NE" },
  { label: "Nigeria", code: "NG" },
  { label: "Niue", code: "NU" },
  { label: "Nordmazedonien", code: "MK" },
  { label: "Nördliche Marianen", code: "MP" },
  { label: "Norfolkinsel", code: "NF" },
  { label: "Norwegen", code: "NO" },
  { label: "Oman", code: "OM" },
  { label: "Osttimor", code: "TL" },
  { label: "Pakistan", code: "PK" },
  { label: "Palau", code: "PW" },
  { label: "Palästina", code: "PS" },
  { label: "Panama", code: "PA" },
  { label: "Papua-Neuguinea", code: "PG" },
  { label: "Paraguay", code: "PY" },
  { label: "Peru", code: "PE" },
  { label: "Philippinen", code: "PH" },
  { label: "Pitcairninseln", code: "PN" },
  { label: "Polen", code: "PL" },
  { label: "Portugal", code: "PT" },
  { label: "Puerto Rico", code: "PR" },
  { label: "Réunion", code: "RE" },
  { label: "Ruanda", code: "RW" },
  { label: "Rumänien", code: "RO" },
  { label: "Russland", code: "RU" },
  { label: "Saint-Martin", code: "MF" },
  { label: "Salomonen", code: "SB" },
  { label: "Sambia", code: "ZM" },
  { label: "Samoa", code: "WS" },
  { label: "San Marino", code: "SM" },
  { label: "São Tomé und Príncipe", code: "ST" },
  { label: "Saudi-Arabien", code: "SA" },
  { label: "Schweden", code: "SE" },
  { label: "Schweiz", code: "CH" },
  { label: "Senegal", code: "SN" },
  { label: "Serbien", code: "RS" },
  { label: "Seychellen", code: "SC" },
  { label: "Sierra Leone", code: "SL" },
  { label: "Simbabwe", code: "ZW" },
  { label: "Singapur", code: "SG" },
  { label: "Slowakei", code: "SK" },
  { label: "Slowenien", code: "SI" },
  { label: "Somalia", code: "SO" },
  { label: "Spanien", code: "ES" },
  { label: "Sri Lanka", code: "LK" },
  { label: "St. Barthélemy", code: "BL" },
  { label: "St. Helena", code: "SH" },
  { label: "St. Kitts und Nevis", code: "KN" },
  { label: "St. Lucia", code: "LC" },
  { label: "St. Pierre und Miquelon", code: "PM" },
  { label: "St. Vincent und die Grenadinen", code: "VC" },
  { label: "Südafrika", code: "ZA" },
  { label: "Sudan", code: "SD" },
  { label: "Südsudan", code: "SS" },
  { label: "Suriname", code: "SR" },
  { label: "Syrien", code: "SY" },
  { label: "Tadschikistan", code: "TJ" },
  { label: "Taiwan", code: "TW" },
  { label: "Tansania", code: "TZ" },
  { label: "Thailand", code: "TH" },
  { label: "Togo", code: "TG" },
  { label: "Tokelau", code: "TK" },
  { label: "Tonga", code: "TO" },
  { label: "Trinidad und Tobago", code: "TT" },
  { label: "Tschad", code: "TD" },
  { label: "Tschechien", code: "CZ" },
  { label: "Tunesien", code: "TN" },
  { label: "Türkei", code: "TR" },
  { label: "Turkmenistan", code: "TM" },
  { label: "Turks- und Caicosinseln", code: "TC" },
  { label: "Tuvalu", code: "TV" },
  { label: "Uganda", code: "UG" },
  { label: "Ukraine", code: "UA" },
  { label: "Ungarn", code: "HU" },
  { label: "Uruguay", code: "UY" },
  { label: "Usbekistan", code: "UZ" },
  { label: "Vanuatu", code: "VU" },
  { label: "Vatikanstadt", code: "VA" },
  { label: "Venezuela", code: "VE" },
  { label: "Wallis und Futuna", code: "WF" },
  { label: "Weihnachtsinsel", code: "CX" },
  { label: "Westsahara", code: "EH" },
  { label: "Zentralafrikanische Republik", code: "CF" },
  { label: "Vereinigte Arabische Emirate", code: "AE" },
  { label: "Vereinigte Staaten", code: "US" },
  { label: "Vereinigtes Königreich", code: "GB" },
  { label: "Vietnam", code: "VN" },
  { label: "Zypern", code: "CY" },
];
